### ISSUE TITLE
Create onboarding package for new members of the community of codebases

### ISSUE THREAD

**Issue by AlbaRoza** [publiccodenet/about#983] opened 2020-12-17 08:42 UTC
Prepare a procedure with different materials once a new person joins a codebase.

These materials could include:
- Leaflet/video of the Foundation: https://github.com/publiccodenet/publiccode.net/issues/184
- Links to our website and repos
- Leaflet/video of the codebase
- Links to the website of the codebase and its repos

Other potential TO DOs:
- Give a talk?
- Share assets?

**Comment by clausmullie** [comment] 2021-12-22 16:34
I am going to close this issue for now for the following reasons:
* The issue is addressed at community members for a codebase under stewardship. Perhaps it is best if the need for this is evaluated at a codebase level (ie a codebase in incubation has many new users who need onboarding). Both Signalen and OpenZaak websites also now have a link to our website, a video, and some other communication materials.
* The issue also includes improving how easily new people can understand and familiarise themselves with what we do. This is something that is being worked on in the website revamp, explainer videos, and general communications effort. 
* This issue has been open for over a year without activity.

**Closed by clausmullie** 2021-12-22 16:34 UTC
